<?php
/**
 * @file
 * Module to import d6 -> d7 content using the Migrate module.
 */


/**
 * Name used to group the migration classes.
 */
define('C4D_MIGRATE_MIGRATION_GROUP', 'c4d_migrate');

/**
 * Implements hook_migrate_api().
 */
function c4d_migrate_migrate_api() {
  $migrations = array();

  $classes = array(
//    'C4dImportArticles',
  );

  $group_name = 'c4d_migrate';

  foreach ($classes as $class_name) {
    $migrations[$class_name] = array(
      'class_name' => $class_name,
      'group_name' => $group_name,
    );
  }

  $api = array(
    'api'        => 2,
    'groups'     => array(
      $group_name => array(
        'title' => t('Import Capacity4dev content'),
      ),
    ),
    'migrations' => $migrations,
  );

  return $api;
}
