<?php
/**
 * @file
 * Module to import d6 -> d7 content using the Migrate module.
 */

/**
 * Name used to group the migration classes.
 */
define('C4D_MIGRATE_MIGRATION_GROUP', 'c4d_migrate');

/**
 * Database name (connection name).
 */
define('C4D_MIGRATE_DATABASE', 'c4d_migrate_database');

/**
 * Database variables (settings form and used in migrations)
 */
define('C4D_MIGRATE_DB_HOST', 'c4d_migrate_db_hostname');
define('C4D_MIGRATE_DB_USER', 'c4d_migrate_db_username');
define('C4D_MIGRATE_DB_PASS', 'c4d_migrate_db_password');
define('C4D_MIGRATE_DB_NAME', 'c4d_migrate_db_database');

/**
 * Files variables (settings form and used in migrations)
 */
define('C4D_MIGRATE_FILES_ROOT', 'c4d_migrate_files_root');

/**
 * Implements hook_migrate_api().
 */
function c4d_migrate_migrate_api() {
  $migrations = array();

  $classes = array(
    'C4dMigrateImportVocabGeo',
    'C4dMigrateImportRoles',
    'C4dMigrateImportUsers',
    'C4dMigrateImportVocabGeo',
    'C4dMigrateImportNodeRegion',
    'C4dMigrateImportNodeTopic',
    'C4dMigrateImportNodeBookPage',
    'C4dMigrateImportNodeHelpPage',
    'C4dMigrateImportNodeArticle',
    'C4dMigrateImportNodeGroup',
    'C4dMigrateImportNodeProject',
    'C4dMigrateImportVocabOGCategories',
    'C4dMigrateImportVocabOGTags',
  );

  $group_name = 'c4d_migrate';

  foreach ($classes as $class_name) {
    $migrations[$class_name] = array(
      'class_name' => $class_name,
      'group_name' => $group_name,
    );
  }

  $api = array(
    'api'        => 2,
    'groups'     => array(
      $group_name => array(
        'title' => t('Import Capacity4dev content'),
      ),
    ),
    'migrations' => $migrations,
  );

  return $api;
}

/**
 * Implements hook_menu().
 */
function c4d_migrate_menu() {
  $items['admin/content/migrate/import'] = array(
    'title'            => 'C4D Import Content',
    'description'      => 'Administer importing content from C4D.',
    'page callback'    => 'drupal_get_form',
    'page arguments'   => array('c4d_migrate_admin_overview_form'),
    'access arguments' => array('administer c4d import'),
    'file'             => 'c4d_migrate.admin.inc',
    'file path'        => drupal_get_path('module', 'c4d_migrate'),
    'type'             => MENU_LOCAL_TASK,
    'weight'           => 20,
  );

  return $items;
}
